afex/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import  url
from afexapp import views

urlpatterns = [
    path('affexapp/', include('afexapp.urls')),
    path('admin/', admin.site.urls),
    #  path('accounts/', include('django.contrib.auth.urls')), 
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    # path('<str:username>/', views.profile, name='profile'),
    # url(r'^(?P<username>[^/]+)/$', views.profile, name='user_profile'),
    path('logout/', views.user_logout, name='logout'),
    path('api/v1/', include('api.urls')),
]

afexapp/urls.py
from django.urls import path

from . import views

app_name = 'afexapp'

urlpatterns = [
    
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('create_task/', views.save_task, name='save_task'),
    # path('', views.profile, name='profile'),
]

api/urls.py
from django.urls import path, include

from . import views

app_name = 'api'

from . import views

urlpatterns = [
    path('', views.Tasks.as_view()),
    # path('<int:pk>/', views.DetailTodo.as_view()),
    # path('login/', views.login),
    path('rest-auth/', include('rest_auth.urls')),
]

afexapp/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# Create your models here.
APPROVED = 'A'
PENDING = 'P'
status = ((APPROVED, 'approved'),
           (PENDING, 'pending') 
)

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    phonenumber = models.CharField(max_length=30, blank=True)
    status = models.CharField(max_length=10, choices=status, default=PENDING)

    def __str__(self):
        return self.user.username

class Tasks(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    #goal_status = models.ForeignKey(GoalStatus, on_delete=models.CASCADE)
    task = models.CharField(max_length=200)
    description = models.CharField(max_length=200, blank=True)
    date = models.DateField(default=datetime.date.today, null=True)



    def __str__(self):
        return self.task        

# @receiver(post_save, sender=settings.AUTH_USER_MODEL)
# def create_auth_token(sender, instance=None, created=False, **kwargs):
#     if created:
#         Token.objects.create(user=instance)

api/models.py
from django.db import models

# Create your models here.

afexapp/forms.py
from django import forms
from afexapp.models import UserProfile, Tasks
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

class UserProfileForm(forms.ModelForm):
 
    class Meta():
        model = UserProfile
        fields = ('phonenumber',)

class TasksForm(forms.ModelForm):
    date = forms.DateField(
        widget=forms.widgets.DateInput(format="%m/%d/%Y"))
    class Meta():
        model = Tasks
        fields = ('task','description', 'date')        

afexapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from afexapp.forms import UserForm,UserProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from afexapp.models import UserProfile, Tasks
# Create your views here.

def index(request):
    # name = User.objects.filter(username=username)
    
    # user = get_object_or_404(User, username__iexact=request.user)
    # # user_status = UserProfile.objects.filter(user=user.pk)
    # task = Tasks.objects.filter(username=user.pk)
    # # task = get_object_or_404(Tasks, username=user.pk)
    # context = {'user': user, 'task':task}
    return render(request,'afex/index.html')

# @login_required
# def login_redirect(request):
#     # username = get_object_or_404(User, username__iexact=username)
#     return HttpResponseRedirect(
#         reverse(profile, kwargs={'username': request.GET.username})) 
      

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def profile(request):

    users = get_object_or_404(User, username__iexact=request.user)
    # user_status = UserProfile.objects.filter(user=user.pk)
    task = Tasks.objects.filter(username=users.pk)
    # task = get_object_or_404(Tasks, username=user.pk)
    context = {'user': users, 'task':task}
    return render(request,'afex/home.html', context)

def save_task(request):
    
    user = request.user
    userid = get_object_or_404(User, pk=user.id)
    
    if request.method == 'POST':
        task = request.POST.get('task')
        description = request.POST.get('description')
        date = request.POST.get('date')
        mymodel = Tasks(username=userid, task=task, description=description, date=date)
        mymodel.save()
        # if mymodel.save():
        return HttpResponseRedirect(reverse('profile'))
     
    return render(request, 'afex/task.html', {}) 

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            # if 'profile_pic' in request.FILES:
            #     print('found it')
            #     profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
      
    return render(request,'afex/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})  

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                # return HttpResponseRedirect(reverse('profile', kwargs={'username': username}))
                return HttpResponseRedirect(reverse('profile'))
                # return HttpResponseRedirect('/%s/'%username)
                
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'afex/login.html', {})                             

api/views.py
from django.shortcuts import render
from rest_framework import generics
from afexapp.models import Tasks
from .serializers import TaskSerializer
from django.contrib.auth import authenticate
from django.views.decorators.csrf import csrf_exempt
from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.status import (
    HTTP_400_BAD_REQUEST,
    HTTP_404_NOT_FOUND,
    HTTP_200_OK
)
from rest_framework.response import Response

# Create your views here.
class Tasks(generics.ListCreateAPIView):
    queryset = Tasks.objects.all()
    serializer_class = TaskSerializer

# def login(request):
#     # username = request.data.get("username")
#     # password = request.data.get("password")
#     username = request.data["username"]
#     password = request.data["password"]
#     if username is None or password is None:
#         return Response({'error': 'Please provide both username and password'},
#                         status=HTTP_400_BAD_REQUEST)
#     user = authenticate(username=username, password=password)
#     if not user:
#         return Response({'error': 'Invalid Credentials'},
#                         status=HTTP_404_NOT_FOUND)
#     token, _ = Token.objects.get_or_create(user=user)
#     return Response({'token': token.key},
#                     status=HTTP_200_OK)    

templates/afex/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'afexapp:register' %}">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            {% comment %} <li><a class="navbar-link" href="{% url 'login' %}">Login</a></li> {% endcomment %}
            <li><a class="navbar-link" href="{% url 'afexapp:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/afex/home.html
{% extends "afex/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    {% comment %} <h1>Welcome to the Djungle !</h1> {% endcomment %}
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
       
            <a href="{% url 'afexapp:save_task' %}">Create a task</a>
            {% if task %}
                <table>
                    <thead>
                        <tr>
                        <th>task</th>
                        <th>Description</th>
                        <th>Due date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in task %}
                        <tr>
                            <td>{{task.task}}</td>
                            <td>{{task.description}}</td>
                            <td>{{task.date}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                <table>
                {% else %}
                <h2>You dont have any task at the moment</h2>
                {% endif %}
         
     {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/afex/index.html
{% extends "afex/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    {% comment %} <h1>Welcome to the Djungle !</h1> {% endcomment %}
    {% comment %} {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
        
     {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %} {% endcomment %}
    <h2>Register or Login if you'd like to</h2>
  </div>
</div>
{% endblock %}

templates/afex/login.html
{% extends 'afex/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'afexapp:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
{% comment %} <form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form> {% endcomment %}
</div>
  </div>
{% endblock %}

templates/afex/registration.html
{% extends "afex/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
        <li><a class="navbar-link" href="{% url 'afexapp:user_login' %}">Login</a></li>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/afex/task.html
{% extends 'afex/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Create a task :</h1>
<form method="post" action="{% url 'afexapp:save_task' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="task">task:</label>
          <input type="text" name="task" placeholder=""><br>
<label for="description">Description:</label>
          <input type="text" name="description" placeholder=""><br>
          <label for="date">Date:</label>
          <input type="date" name="date" placeholder=""><br>
<input type="submit" name="" value="create task">
</form>
{% comment %} <form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form> {% endcomment %}
</div>
  </div>
{% endblock %}